import { LatestManga } from "./comic-info";
import { PopularManga } from "./popular-comic";

export const sampleItems: LatestManga[] = [
    {
        id: "1",
        title: "One Piece",
        url: "/manga/one-piece",
        cover: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=300&h=400&fit=crop",
        type: "Manhua",
        isNew: true,
        status: "Ongoing",
        chapters: [
            {
                url: "/manga/one-piece/chapter-1100",
                title: "Chapter 1100",
                timeago: "2 hours ago",
            },
            {
                url: "/manga/one-piece/chapter-1099",
                title: "Chapter 1099",
                timeago: "1 day ago",
            },
        ],
    },
    {
        id: "2",
        title: "Attack on Titan",
        url: "/manga/attack-on-titan",
        cover: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=300&h=400&fit=crop",
        type: "Manga",
        isNew: false,
        status: "Completed",
        chapters: [
            {
                url: "/manga/attack-on-titan/chapter-139",
                title: "Chapter 139",
                timeago: "3 days ago",
            },
        ],
    },
    {
        id: "3",
        title: "Demon Slayer",
        url: "/manga/demon-slayer",
        cover: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=300&h=400&fit=crop",
        type: "Manhwa",
        isNew: true,
        status: "Ongoing",
        chapters: [
            {
                url: "/manga/demon-slayer/chapter-205",
                title: "Chapter 205",
                timeago: "5 hours ago",
            },
            {
                url: "/manga/demon-slayer/chapter-204",
                title: "Chapter 204",
                timeago: "2 days ago",
            },
            {
                url: "/manga/demon-slayer/chapter-203",
                title: "Chapter 203",
                timeago: "4 days ago",
            },
        ],
    },
    {
        id: "4",
        title: "My Hero Academia",
        url: "/manga/my-hero-academia",
        cover: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=400&fit=crop",
        type: "Manga",
        isNew: false,
        status: "Ongoing",
        chapters: [
            {
                url: "/manga/my-hero-academia/chapter-400",
                title: "Chapter 400",
                timeago: "6 hours ago",
            },
            {
                url: "/manga/my-hero-academia/chapter-399",
                title: "Chapter 399",
                timeago: "1 day ago",
            },
        ],
    },
    {
        id: "5",
        title: "Jujutsu Kaisen",
        url: "/manga/jujutsu-kaisen",
        cover: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=300&h=400&fit=crop",
        type: "Manga",
        isNew: true,
        status: "Ongoing",
        chapters: [
            {
                url: "/manga/jujutsu-kaisen/chapter-250",
                title: "Chapter 250",
                timeago: "1 hour ago",
            },
            {
                url: "/manga/jujutsu-kaisen/chapter-249",
                title: "Chapter 249",
                timeago: "3 hours ago",
            },
        ],
    },
    {
        id: "6",
        title: "Jujutsu Kaisen",
        url: "/manga/jujutsu-kaisen",
        cover: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=300&h=400&fit=crop",
        type: "Manga",
        isNew: true,
        status: "Ongoing",
        chapters: [
            {
                url: "/manga/jujutsu-kaisen/chapter-250",
                title: "Chapter 250",
                timeago: "1 hour ago",
            },
            {
                url: "/manga/jujutsu-kaisen/chapter-249",
                title: "Chapter 249",
                timeago: "3 hours ago",
            },
        ],
    },
];

export const popularMangasSample: PopularManga[] = [
    {
        id: 1,
        title: "Solo Leveling",
        url: "solo-leveling",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/Chotto-Dake-ai-ga-Omoi-Dark-Elf-ga-Isekai-Kara-Oikakete-Kita-1-211x300.jpg",
        author: "Chugong",
        totalView: 15000,
        rating: 8,
        createdDate: "2024-01-01",
        lastChapter: "Chapter 179",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Action", "Adventure", "Fantasy"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 1
    },
    {
        id: 2,
        title: "One Piece",
        url: "one-piece",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/Chotto-Dake-ai-ga-Omoi-Dark-Elf-ga-Isekai-Kara-Oikakete-Kita-1-211x300.jpg",
        author: "Eiichiro Oda",
        totalView: 12000,
        rating: 8,
        createdDate: "2024-01-05",
        lastChapter: "Chapter 1110",
        modifiedBy: "Editor",
        createdBy: "Admin",
        genres: ["Action", "Shounen"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manga",
        colored: false,
        rank: 2
    },
    {
        id: 5,
        title: "The Beginning After The End",
        url: "the-beginning-after-the-end",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/Head-Chronicles-of-the-Demon-Faction-231x300.jpg",
        author: "TurtleMe",
        totalView: 850000,
        rating: 7,
        createdDate: "2023-05-12",
        lastChapter: "Chapter 175",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Action", "Fantasy", "Isekai"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 6,
        title: "Eleceed",
        url: "eleceed",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/All-Attribute-Great-Sage-1-216x300.png",
        author: "Son Jeho",
        totalView: 620000,
        rating: 4.8,
        createdDate: "2023-06-15",
        lastChapter: "Chapter 280",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Action", "Comedy", "Supernatural"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 4
    },
    {
        id: 7,
        title: "Mercenary Enrollment",
        url: "mercenary-enrollment",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/Komik-Magic-Emperor-226x300.jpg",
        author: "YC",
        totalView: 540000,
        rating: 4.7,
        createdDate: "2023-07-20",
        lastChapter: "Chapter 150",
        modifiedBy: "Mod",
        createdBy: "Admin",
        genres: ["Action", "School Life"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 8,
        title: "Black Clover",
        url: "black-clover",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/Komik-Magi-Craft-Meister-210x300.jpeg",
        author: "Yūki Tabata",
        totalView: 900000,
        rating: 4.6,
        createdDate: "2023-01-10",
        lastChapter: "Chapter 368",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Shounen", "Magic", "Action"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manga",
        colored: false,
        rank: 3
    },
    {
        id: 9,
        title: "Omniscient Reader",
        url: "omniscient-reader",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/A2-I-Became-the-Despised-Granddaughter-of-the-Murim-Family-210x300.jpg",
        author: "Sing Shong",
        totalView: 780000,
        rating: 7,
        createdDate: "2023-03-05",
        lastChapter: "Chapter 190",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Action", "Psychological", "Fantasy"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 10,
        title: "Wind Breaker",
        url: "wind-breaker",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/A2-I-Became-a-Sales-Prodigy-207x300.jpg",
        author: "Jo Yongseok",
        totalView: 430000,
        rating: 4.8,
        createdDate: "2023-08-12",
        lastChapter: "Chapter 470",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Sports", "Drama", "Action"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 11,
        title: "The Great Mage Returns",
        url: "great-mage-returns",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/IBecameCover-222x300.jpg",
        author: "Barnacle",
        totalView: 310000,
        rating: 4.5,
        createdDate: "2023-09-01",
        lastChapter: "Chapter 185",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Fantasy", "Action"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 12,
        title: "Blue Lock",
        url: "blue-lock",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/Head-I-Became-The-King-by-Scavenging-225x300.jpg",
        author: "Muneyuki Kaneshiro",
        totalView: 670000,
        rating: 4.7,
        createdDate: "2023-02-28",
        lastChapter: "Chapter 240",
        modifiedBy: "Editor",
        createdBy: "Admin",
        genres: ["Sports", "Shounen"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manga",
        colored: false,
        rank: 3
    },
    {
        id: 13,
        title: "Nano Machine",
        url: "nano-machine",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/A2-I-Became-The-Genius-Bastard-Of-A-Noble-Dark-Clan-210x300.jpg",
        author: "Han-Joong-Wueol-Ya",
        totalView: 590000,
        rating: 4.8,
        createdDate: "2023-04-14",
        lastChapter: "Chapter 180",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Martial Arts", "Sci-fi", "Action"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 14,
        title: "Lookism",
        url: "lookism",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/Head-I-Became-The-Games-Biggest-Villain-226x300.jpg",
        author: "Park Tae-jun",
        totalView: 890000,
        rating: 4.7,
        createdDate: "2022-11-20",
        lastChapter: "Chapter 480",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Drama", "Action", "School Life"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 15,
        title: "Return of Mount Hua Sect",
        url: "mount-hua-sect",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/A2-I-Became-the-Despised-Granddaughter-of-the-Murim-Family-210x300.jpg",
        author: "Biga",
        totalView: 720000,
        rating: 7,
        createdDate: "2023-10-05",
        lastChapter: "Chapter 105",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Martial Arts", "Comedy", "Action"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 16,
        title: "SSS-Class Suicide Hunter",
        url: "sss-suicide-hunter",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/A2-Chronicles-of-the-Reincarnated-Demon-God-210x300.jpg",
        author: "Shin Noah",
        totalView: 410000,
        rating: 7,
        createdDate: "2023-05-30",
        lastChapter: "Chapter 110",
        modifiedBy: null,
        createdBy: "Admin",
        genres: ["Fantasy", "Action", "Drama"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manhwa",
        colored: true,
        rank: 3
    },
    {
        id: 17,
        title: "Kingdom",
        url: "kingdom",
        mangaAvatarUrl: "https://komik25.com/wp-content/uploads/2025/04/Head-I-Became-The-King-by-Scavenging-225x300.jpg",
        author: "Yasuhisa Hara",
        totalView: 950000,
        rating: 7,
        createdDate: "2022-01-01",
        lastChapter: "Chapter 780",
        modifiedBy: "System",
        createdBy: "Admin",
        genres: ["Historical", "Military", "Action"],
        mangaCategory: "Manhwa",
        chapters: null,
        type: "Manga",
        colored: false,
        rank: 3
    }
];